name: Run Trading Bot every 5 minutes

on:
  schedule:
    #- cron: '*/5 * * * *'  # ทุก 5 นาที
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4

      - name: Verify installation
        run: |
          python -c "from binance import __version__ as v; print(f'Binance connector version: {v}')"
          python -c "import requests; print(f'Requests version: {requests.__version__}')"
      
      - name: Run bot.py
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}        
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
        run: python botkey.py
